// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

public class Notification
{
	private string subject;
	private string timeAgo;
	private long time;
	private int noteNumber;
	private bool read;
	private string text;

	public Notification (string subject, string timeAgo, long time, int noteNumber, bool read, string text)
	{
		this.subject = subject;
		this.timeAgo = timeAgo;
		this.time = time;
		this.noteNumber = noteNumber;
		this.read = read;
		this.text = text;
	}

	public string Subject {
		get {
			return this.subject;
		}
	}
	
	public string TimeAgo {
		get {
			return this.timeAgo;
		}
	}
	
	public long Time {
		get {
			return this.time;
		}
	}
	
	public int NoteNumber {
		get {
			return this.noteNumber;
		}
	}
	
	public bool Read {
		get { return this.read; }
		set { this.read = value; }
	}
	
	public string Text {
		get {
			return this.text;
		}
	}

}


